sudo: false
language: python
matrix:
  include:
  - os: linux
    dist: bionic
    python: "3.6"
  - os: linux
    dist: bionic
    python: "3.7"
  - os: linux
    dist: bionic
    python: "3.8"
  - os: linux
    dist: bionic
    python: "3.9-dev"
  - os: osx
    osx_image: xcode12.2
    language: generic
    before_install:
        - brew install python@3.8
        - pip3 install virtualenv
install:
#  - scripts/travis.sh pip install pip-accel
  - pip3 install -U setuptools --upgrade
  - scripts/travis.sh pip3 install coveralls
  - scripts/travis.sh pip3 install --requirement=requirements-checks.txt
  - scripts/travis.sh pip3 install --requirement=requirements-tests.txt
  - scripts/travis.sh LC_ALL=C pip3 install .
script:
#  - scripts/travis.sh make check
  - scripts/travis.sh make test
after_success:
  - scripts/travis.sh coveralls
branches:
  except:
    - /^[0-9]/
